--Step 1: Create Contacts Table
CREATE TABLE IF NOT EXISTS CONTACTS (
    ID BINARY(16) PRIMARY KEY DEFAULT (UUID_TO_BIN(UUID())),
    CLASSCODE TEXT NOT NULL,
    CREATETIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    EDITTIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FIRSTNAME TEXT NOT NULL,
    LASTNAME TEXT NOT NULL
);

--Step 2: Add Date of Birth column
ALTER TABLE CONTACTS
ADD DOB TIMESTAMP;