CREATE TABLE IF NOT EXISTS CONTACTS (
    ID BINARY(16) PRIMARY KEY DEFAULT (UUID_TO_BIN(UUID())),
    CREATETIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    EDITTIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FIRSTNAME TEXT NOT NULL,
    LASTNAME TEXT NOT NULL
);