CREATE TABLE IF NOT EXISTS contacts (
    id BINARY(16) PRIMARY KEY DEFAULT (UUID_TO_BIN(UUID())),
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    firstName TEXT NOT NULL,
    lastName TEXT NOT NULL
);